"""-

Revision ID: b4d1df1237c3
Revises: 7d78bf1bacc0
Create Date: 2019-06-30 23:21:36.189276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d1df1237c3'
down_revision = '7d78bf1bacc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('year', table_name='demo_chart2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('year', 'demo_chart2', ['year'], unique=True)
    # ### end Alembic commands ###
